### ISSUE TITLE
workflow failing after changing to new syntax in entrypoint.sh

### ISSUE THREAD

**Issue by jazmc** [jsmrcaga/action-netlify-deploy#38]
Hi!
First of all, thanks to all contributors for this extremely useful repository!

With the latest merge #37 where the syntax of entrypoint.sh was changed, our workflow stopped passing. Here are the last lines of GitHub actions workflow log:

```sh
(...)
- Uploading 0 files
✔ Finished uploading 0 assets
- Waiting for deploy to go live...
✔ Deploy is live!
Error: Unable to process file command 'env' successfully.
Error: Invalid format 'Deploying to main site URL...'
```
Then the workflow job fails, but from Netlify control panel you can see that the app has deployed successfully. 

I guess this could be a syntax error in the echo statements, see discussion about a similar error here: 
https://github.com/orgs/community/discussions/24952

**Comment by jsmrcaga** [comment]
Thanks Jasmin! I'm glad you find the repo useful and I'm so thankful to all the contributors as well.

It might be the multiline indeed. I feel a little dumb since I asked @H4K1 to use the single-line syntax 🙈 .
Would you be willing to try and see if the multi-line syntax fixes this @jazmc and open a PR? I'm not sure I'm gonna have the time in the coming days

**Comment by oshima-gangan** [comment]
@jsmrcaga 
Hi,
Thank you very much for letting me use convenient actions.

I have created a pull request with modified code, so please review it.
- #39

**Comment by jsmrcaga** [comment]
Thanks @oshima-gangan , merged!
