### ISSUE TITLE
Error: Process completed with exit code 130 - Issue with Netlify deployment  

### ISSUE THREAD

**Issue by rbneem** [jsmrcaga/action-netlify-deploy#52]
Since yesterday we are seeing all our deployments to Netlify are failing in GitHub actions with the above error.

I see we didn't update workflows the same workflow was used 2 days back and all builds are successful, I re-verified all the env var's Site ID and Netlify Access Token all look good but still no luck. 

The error message is not at all helpful in this case. Can anyone help me out here?
![Screenshot 2023-08-22 191449](https://github.com/jsmrcaga/action-netlify-deploy/assets/69182857/514f86e8-e29b-4467-b94a-be8dc87a2474)

**Comment by jsmrcaga** [comment]
Hello @rbneem, sadly I have not been able to find any sources indicating what this error might be.
The closest I've found is [this question on the forums](https://answers.netlify.com/t/netlify-auto-deploys-before-github-action-has-finished-updating-the-code/49429) but does not seem completely related.

I know @tpluscode has been having some issues as well. This action uses the pre-installed netlify cli on GitHub runners, so it was probably caused by an update.

Could you try deploying this "from your machine" after updating the CLI and see if you see any difference ?
I'm sorry I can't be of any more help

**Comment by Nyeova** [comment]
Having the same issue here....
any temporary workaround for a manual deployment?

**Comment by tpluscode** [comment]
Oh, I just found that I can no longer deploy. `exit code 130`. This is not the issue I reported earlier.

@rbneem any news from Netlify on the matter?

**Comment by tpluscode** [comment]
Correction, `--dir` is still needed apparently. Dunno why it worked locally without it but I had to keep it in the job... 

https://github.com/hypermedia-app/shape-to-query/actions/runs/6470007726/job/17565237973?pr=230
